twig_component:
    anonymous_template_directory: 'components/'
    defaults:
        # Namespace & directory for components
        App\Components\common\: 'components/common'
        App\Components\dashboard\: 'components/dashboard'

live_component:
      anonymous_template_directory: 'components/'
      defaults:
        # Namespace & directory for components
        App\Components\common\: 'components/common'
        App\Components\dashboard\: 'components/dashboard'